[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "export-capcut-pro-video-free"
version = "1.0.0"
description = "Export Capcut Pro Video Free - High-performance recovery engine to decrypt, unlock, and export unplayable CapCut & JianYing draft cache videos."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Shanto", email = "pikadexofc@users.noreply.github.com" }
]
keywords = [
    "export-capcut-pro-video-free",
    "capcut-pro",
    "capcut-free",
    "capcut-pro-free",
    "capcut",
    "jianying",
    "video-recovery",
    "bdve",
    "video-decryption",
    "moov-atom-not-found",
    "mp4-recovery",
    "ffmpeg",
    "bytedance"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/pikadexofc/export-capcut-pro-video-free"
Repository = "https://github.com/pikadexofc/export-capcut-pro-video-free"
Issues = "https://github.com/pikadexofc/export-capcut-pro-video-free/issues"

[project.scripts]
export-capcut-pro-video-free = "capcut_cache_recover.cli:main"
export-capcut-gui = "capcut_cache_recover.gui:launch_gui"
capcut-pro-free = "capcut_cache_recover.cli:main"
capcut-cache-recover = "capcut_cache_recover.cli:main"
