[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "capcut-cache-recover"
version = "1.0.2"
description = "CapCut Cache Recover - Forensic video stream recovery and cache salvage engine for CapCut & JianYing draft caches."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "PixelPie Media (Md. Zobaed Islam Shanto)", email = "pikadexofc@users.noreply.github.com" }
]
keywords = [
    "capcut-cache-recover",
    "capcut",
    "jianying",
    "forensic-recovery",
    "video-repair",
    "stream-recovery",
    "bdve",
    "bdve-type1",
    "moov-atom-not-found",
    "mp4-recovery",
    "multimedia",
    "bytedance"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/pikadexofc/export-capcut-pro-video-free"
Repository = "https://github.com/pikadexofc/export-capcut-pro-video-free"
Issues = "https://github.com/pikadexofc/export-capcut-pro-video-free/issues"

[project.scripts]
capcut-cache-recover = "capcut_cache_recover.cli:main"
capcut-gui = "capcut_cache_recover.gui:launch_gui"
export-capcut-pro-video-free = "capcut_cache_recover.cli:main"
export-capcut-gui = "capcut_cache_recover.gui:launch_gui"

[tool.setuptools.packages.find]
where = ["."]
include = ["capcut_cache_recover*"]
exclude = ["assets*", "scripts*", "tests*"]
